### ISSUE TITLE
请问有用XGB在知乎的数据上做测试了吗？效果如何？

### ISSUE THREAD

**Issue by xinyuwufei** [xyx323/ZhiHuKanShan#3]
repo主你好，
请问有用XGB在知乎的数据上做测试了吗？效果如何？

**Comment by DuankangFu** [comment]
您好，这个项目还没有完成 , 还没有用XGBoost完全实现。

**Comment by xinyuwufei** [comment]
谢谢回复 ，那还想请教一下 你使用kmean测试了一下数据吗？baseline效果如何？
